export function createInitialState() {
  return {
    step: 1,
    apiBaseUrl: "http://127.0.0.1:8787",
    project: {
      subject: "",
      frameworkId: "",
      grade: "",
      schoolName: "",
      schoolYear: "",
      semester: "",
      examType: "",
      teacherName: "",
      version: "",
      range: "",
    },
    materialText: "",
    planRows: [
      { questionType: "選擇題", count: 20, score: 2, isGroup: false, groupCount: 1, subScores: [] },
      { questionType: "是非題", count: 10, score: 2, isGroup: false, groupCount: 1, subScores: [] },
      { questionType: "填充題", count: 10, score: 2, isGroup: false, groupCount: 1, subScores: [] },
      { questionType: "學力檢測題", count: 4, score: 2, isGroup: true, groupCount: 4, subScores: [2, 3] },
    ],
    objectiveInput: "",
    objectives: [],
    objectivePlans: [],
    intents: [],
    sections: [],
    items: [],
    partialResult: null,
    messages: [],
    errors: [],
    checkedChineseSubcategories: ["正確字音", "確認字形", "分辨部首", "字詞釋義", "句型辨識", "文句組成", "常用修辭", "提取訊息", "推論訊息", "主題習寫"],
    customTargetScores: {},
  };
}
